### ISSUE TITLE
Yaml parser fails when handling "!Ref" function form

### ISSUE THREAD

**Issue by suddi** [steven-bruce-au/dynamodb-local-cloud-formation#3]
The yaml parser fails when handling the "!Ref" function form used to reference values provided in `Parameters` with the following error stack:

````
Traceback (most recent call last):
  File "../dynamodb-local-cloudformation/parse.py", line 25, in <module>
    for table in cloudFormationParser.parse_cloud_formation_template(args.filename):
  File "/home/py/dynamodb-local-cloudformation/dynamodb_cloud_formation/cloud_formation_parser.py", line 29, in parse_cloud_formation_template
    cloud_formation_json = self.load_yaml(file_name)
  File "/home/py/dynamodb-local-cloudformation/dynamodb_cloud_formation/cloud_formation_parser.py", line 24, in load_yaml
    yamlData = yaml.load(fileHandle)
  File "/usr/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python2.7/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!Ref'
````

According to [documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html), we can reference `Parameters` using `!Ref` function form or the full dictionary form. Both of these methods are not working with `dynamodb-local-cloud-formation`.

**Comment by suddi** [comment]
Closing, I had missed the `Known Issues` section...
